// <auto-generated />
using System;
using GhostCurve.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GhostCurve.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GhostCurveDbContext))]
    partial class GhostCurveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GhostCurve.Domain.Models.PerformanceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AvgRoiPercent")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("avg_roi_percent");

                    b.Property<int>("LossCount")
                        .HasColumnType("integer")
                        .HasColumnName("loss_count");

                    b.Property<decimal>("MaxDrawdownPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("max_drawdown_percent");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("SnapshotAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at_utc");

                    b.Property<decimal>("SolBalance")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("sol_balance");

                    b.Property<decimal>("TotalPortfolioValue")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("total_portfolio_value");

                    b.Property<decimal>("TotalRealizedPnl")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("total_realized_pnl");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("integer")
                        .HasColumnName("total_trades");

                    b.Property<decimal>("TotalUnrealizedPnl")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("total_unrealized_pnl");

                    b.Property<int>("WinCount")
                        .HasColumnType("integer")
                        .HasColumnName("win_count");

                    b.Property<decimal>("WinRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("win_rate");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "SnapshotAtUtc")
                        .HasDatabaseName("ix_performance_snapshots_session");

                    b.ToTable("performance_snapshots", (string)null);
                });

            modelBuilder.Entity("GhostCurve.Domain.Models.SimulatedTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("DelayMs")
                        .HasColumnType("integer")
                        .HasColumnName("delay_ms");

                    b.Property<DateTimeOffset>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at_utc");

                    b.Property<string>("Mint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mint");

                    b.Property<decimal?>("RealizedPnl")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("realized_pnl");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<short>("Side")
                        .HasColumnType("smallint")
                        .HasColumnName("side");

                    b.Property<decimal>("SimulatedPrice")
                        .HasPrecision(28, 18)
                        .HasColumnType("numeric(28,18)")
                        .HasColumnName("simulated_price");

                    b.Property<decimal>("SlippageBps")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("slippage_bps");

                    b.Property<decimal>("SolAmount")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("sol_amount");

                    b.Property<long>("SourceTradeEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_trade_event_id");

                    b.Property<decimal>("TokenAmount")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("token_amount");

                    b.Property<decimal>("VSolAtExecution")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("v_sol_at_execution");

                    b.Property<decimal>("VTokensAtExecution")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("v_tokens_at_execution");

                    b.HasKey("Id");

                    b.HasIndex("SourceTradeEventId")
                        .HasDatabaseName("ix_simulated_trades_source_event");

                    b.HasIndex("SessionId", "Mint", "ExecutedAtUtc")
                        .HasDatabaseName("ix_simulated_trades_session_mint");

                    b.ToTable("simulated_trades", (string)null);
                });

            modelBuilder.Entity("GhostCurve.Domain.Models.SimulationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<decimal?>("FinalSolBalance")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("final_sol_balance");

                    b.Property<decimal>("InitialSolBalance")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("initial_sol_balance");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id");

                    b.ToTable("simulation_sessions", (string)null);
                });

            modelBuilder.Entity("GhostCurve.Domain.Models.TradeEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("BondingCurveKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bonding_curve_key");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("MarketCapSol")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("market_cap_sol");

                    b.Property<string>("Mint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mint");

                    b.Property<decimal>("NewTokenBalance")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("new_token_balance");

                    b.Property<string>("Pool")
                        .HasColumnType("text")
                        .HasColumnName("pool");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature");

                    b.Property<decimal>("SolAmount")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("sol_amount");

                    b.Property<decimal>("TokenAmount")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("token_amount");

                    b.Property<string>("TraderPublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trader_public_key");

                    b.Property<short>("TxType")
                        .HasColumnType("smallint")
                        .HasColumnName("tx_type");

                    b.Property<decimal>("VSolInBondingCurve")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("v_sol_in_bonding_curve");

                    b.Property<decimal>("VTokensInBondingCurve")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("v_tokens_in_bonding_curve");

                    b.HasKey("Id");

                    b.HasIndex("Mint")
                        .HasDatabaseName("ix_trade_events_mint");

                    b.HasIndex("Signature")
                        .IsUnique();

                    b.HasIndex("TraderPublicKey", "ReceivedAtUtc")
                        .HasDatabaseName("ix_trade_events_trader_received");

                    b.ToTable("trade_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
